### ISSUE TITLE
I don't know for sure if this is a bug or not, but things are spawning with more armor than I think they should be spawning with. Drones with 4 armor, Purifiers with 6, Basic Advent Mecs with 3 before getting hit and generating more. Compared to the Gatekeeper's 2 armor and shred doing 1, the high armor feels out of place

### ISSUE THREAD

**Issue by Whats-an-Airport** [Grobobobo/WarOfTheChosenRebalanced#10]
![20220520231427_1](https://user-images.githubusercontent.com/106243012/170250216-3cab6e11-5fe5-494e-a008-bc2747adff03.jpg)
![20220522163330_1](https://user-images.githubusercontent.com/106243012/170250219-c080eea6-882f-4f79-bac4-1953d461393e.jpg)

**Comment by Whats-an-Airport** [comment]
And yes, that Purifier was broken. Didn't move or fire (excluding return fire when shot).

**Comment by Grobobobo** [comment]
What's the force level for these units?

**Comment by Grobobobo** [comment]
Purifier was accidentally spawning in FL1, fixed now.
