### ISSUE TITLE
This word salad of a Super Priest spawning in. Force 20-21, Advent Facility.

### ISSUE THREAD

**Issue by Whats-an-Airport** [Grobobobo/WarOfTheChosenRebalanced#11]
![20220525014134_1](https://user-images.githubusercontent.com/106243012/170250999-158c3377-981f-4fa4-bd51-0648c398c206.jpg)
![20220525014137_1](https://user-images.githubusercontent.com/106243012/170251007-b89a4353-3439-44d5-9051-bf43b31e07fa.jpg)

**Comment by Grobobobo** [comment]
This should be fixed already.
