### ISSUE TITLE
Magnet grenades aren't affected by the grenade launcher primary while Plasma grenades are.

### ISSUE THREAD

**Issue by Whats-an-Airport** [Grobobobo/WarOfTheChosenRebalanced#13]
![20220605162714_1](https://user-images.githubusercontent.com/106243012/172360774-7a57cdc0-49f0-46e5-bf16-057764159949.jpg)
![20220605162719_1](https://user-images.githubusercontent.com/106243012/172360782-01a8d798-cde8-4113-bed2-5030f49f0206.jpg)

**Comment by wdanny69** [comment]
So I found out the reason and its kinda janky and idk why. if you look at your bar you can see two versions of the skill, one of them IS affected by the grenade launcher range and the either isn't not clue why its like this.

**Comment by Grobobobo** [comment]
Do we know if it's magnetic grenade specific, and not some bug with packmaster? I'll need to test this.

**Comment by Grobobobo** [comment]
I think this is actually a full kit/salvo bug. Might be fixed next update, check if it'll still apply.
