### ISSUE TITLE
Serial Bugged or outdated localization

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#25]
Serial states that each kill decreases the damage dealt but base damage seems to appear the same regardless of amount of kills and the ui also shows no damage reduction.

**Comment by Grobobobo** [comment]
How many kills did you get with it?

**Comment by wdanny69** [comment]
I checked a couple times where i get like a couple kills

**Comment by Grobobobo** [comment]
I'll be getting rid of serial soon enough (and probably put it on a chosen weapon which then will probably not need a damage reduction?) so it's not that big of a deal, but I'll investigate anyway.

**Comment by Grobobobo** [comment]
Found it, fixed.
