### ISSUE TITLE
Chosen in council missions.

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#28]
Are chosen supposed to appear in council missions?
If yes, a balance thought, 10 turns is feels fairly short to fight all the enemies and make it to the objective and evac.
Played a mission by console killing the warlock and its summons to get a feel for the mission and i still didn't have enough time, had to use intervention twice and still had a turn left on the timer.

**Comment by Grobobobo** [comment]
They shouldn't, and they won't now.
