### ISSUE TITLE
Berserker doing nothing

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#34]
For some reason this mission in particular the berserker was just straight not dealing any damage against lost, pointlessly smacking one for the entirety of the mission. This was also an armored berserker which strangely didn't have the "bladestorm" ability like previous ones I fought did. Perhaps something went wrong in spawning the unit.

[save_zerker doing no damage.zip](https://github.com/Grobobobo/WarOfTheChosenRebalanced/files/8940473/save_zerker.doing.no.damage.zip)

**Comment by Grobobobo** [comment]
The save crashes on my machine. What Force level was that?

**Comment by wdanny69** [comment]
I dont remember but it might've been around 12?

**Comment by Grobobobo** [comment]
Did this end up happening again?
