### ISSUE TITLE
Walk fire and mayhem may not be neutral as weapon progresses

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#41]
At laser tier it seemed like the penalty and the gain from mayhem counteres each other reaching 100% base damage but at mag tier and it seems like overall the damage is reduced by 1 instead of supposedly expected 0.

**Comment by Grobobobo** [comment]
might be fixed next update, check if it'll still apply.

**Comment by Grobobobo** [comment]
Seems to be a rounding error, I can probably just make it remove the suppression/walk fire damage penalty instead, but I'm not sure if i won't want to change the damage modifiers at some point some more. Not worth bothering much for now.

**Comment by Grobobobo** [comment]
Fixed by changing mayhem to remove the penalty instead.
