### ISSUE TITLE
Loadout bug with rockets

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#44]
When making loadouds and then entering mission, i suddenly have both regular and shredder rockets equipped despite loadout only showing one. Unsure how it works but it might be related to carrying the extra rocket items last mission and for some reason disappearing when loading out a new mission. Was checking around and if you press the x icon on the grenade slot to remove it, the rocket appears.
[SaveData.zip](https://github.com/Grobobobo/WarOfTheChosenRebalanced/files/8952374/SaveData.zip)

**Comment by Grobobobo** [comment]
This also might be caused by the full kit bug.

**Comment by Grobobobo** [comment]
Probably fixed already.
