### ISSUE TITLE
New suppressor effect applying to other attacks.

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#49]
The new suppressor effect for extra aim/crit is also applying to other attacks. Noticed it on shinobis who suddenly have 55% crit but it also appears on other attacks.

**Comment by Grobobobo** [comment]
What do you mean by other attacks?

**Comment by wdanny69** [comment]
Sorry should have been more specific, the bonuses applies to other attacks such as pistols or swords and i assume its meant only for the primary.

**Comment by Grobobobo** [comment]
Might be fixed next update, check if you can.

**Comment by Grobobobo** [comment]
Fixed with the next update.
