### ISSUE TITLE
Some covert actions have no ambush chance

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#51]
unsure if this is intended but some covert actions seem to not be able to be ambushed. the ones that do that i've noticed seems related to going after advent (chosen hunt, recover loot, reduce avatar)

**Comment by Grobobobo** [comment]
I believe this isn't a bug, at most it can be a balance issue, but I don't want to say that yet.

**Comment by Grobobobo** [comment]
Fixed Next Version.
