### ISSUE TITLE
Refined Elerium Covert Action

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#52]
Strangely got this covert action which grants a rocket craftin component but also has some blank components. Completing it grants a refined elerium and the tactical nuke project which also doesn't appear.

![image](https://user-images.githubusercontent.com/39199279/174919464-2e81c8a6-340d-4180-995b-fad5453857a1.png)

**Comment by Grobobobo** [comment]
Fixed.
