### ISSUE TITLE
purifier leader has missing name and broken ai

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#6]
purifier leader pod does not have a name and appears to stay idle never spending their turn ever
[save_lwotcr bug purifier leader idle.zip](https://github.com/Grobobobo/WarOfTheChosenRebalanced/files/8599029/save_lwotcr.bug.purifier.leader.idle.zip)

**Comment by Grobobobo** [comment]
Fixed.
