### ISSUE TITLE
Resistance Informant DE makes Retal Detection harder

### ISSUE THREAD

**Issue by Blacklight076** [Grobobobo/WarOfTheChosenRebalanced#60]
Revert this to vanilla? iirc it was -2 weeks until next retal
the LW2/LWOTC version has no effect except for blocking an actual DE

![image](https://user-images.githubusercontent.com/107238742/176738395-5e8c176b-08e2-4a05-aa60-662edcbc6c1b.png)

**Comment by Grobobobo** [comment]
I've removed the Dark event since it doesn't fit the permament upgrades system anyway.
