### ISSUE TITLE
Priest with holy warrior and turning shoggoth

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#62]
When a priest turns into a shoggoth, the effect remains until you kill the target. killing the shoggoth will not remove the effect.

**Comment by Grobobobo** [comment]
I'll either make it so priests can't become shoggoths, or the holy warrior effect is removed on transformation.

**Comment by Grobobobo** [comment]
Excluded the purge priest from the potential shoggoth targets.
