### ISSUE TITLE
Sawed off reload available during a movement action

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#64]
The sawed off reload ability is still available and usable with a movement action.

**Comment by Grobobobo** [comment]
What cause the "move" action?

**Comment by wdanny69** [comment]
it was whirlwind on shinobi

**Comment by Grobobobo** [comment]
And you're sure it was the only action it had?

**Comment by wdanny69** [comment]
yes, it was the only normal action available

**Comment by wdanny69** [comment]
seems like i misinterpreted how many actions i had left.
