### ISSUE TITLE
Armor Piercing Rounds ignore 5 armor instead of the advertised 2

### ISSUE THREAD

**Issue by Whats-an-Airport** [Grobobobo/WarOfTheChosenRebalanced#7]

**Comment by Grobobobo** [comment]
![image](https://user-images.githubusercontent.com/50756826/170269689-5559ceb0-5a4b-4dce-8b01-6ef1b1d4ee2f.png)
Just checked it, they work as advertised. Are you sure your soldier does not have penetration perks like heat ordnance, or you're running a mod that might mess with the AP round config value?

**Comment by Whats-an-Airport** [comment]
Oh shit, you're right, I think all the gunners I put AP rounds on had Heat Ordinance. My bad. They should be working fine.
