### ISSUE TITLE
What is intended base hp of templar.

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#71]
So with gatecrasher stats are not randomized and are fixed at the average. For templar they start at 5 hp which seems really low compared to base soldiers at 8 hp. I dont think this happened to other heroes but I forgot.

**Comment by Grobobobo** [comment]
It's possible that they're not excluded from not created equally, are their other stats higher?

**Comment by wdanny69** [comment]
confirmed that templar is being affected by NCE regardless of being in starting squad

**Comment by Grobobobo** [comment]
Hero classes are now excluded from NCE.
