### ISSUE TITLE
Death Dealer not providing all bonuses correctly

### ISSUE THREAD

**Issue by Blacklight076** [Grobobobo/WarOfTheChosenRebalanced#77]
![image](https://user-images.githubusercontent.com/107238742/179442862-cb434ac4-a53e-4ba5-83d5-5f6180d6cbc3.png)

death dealer still gives 25 crit chance outside of shadow?

![image](https://user-images.githubusercontent.com/107238742/179442891-793e9297-09be-4b64-accd-179cc1f78198.png)

the +2 crit damage is there when in shadow, but not the 10 aim

**Comment by Grobobobo** [comment]
Fixed next version.
