### ISSUE TITLE
The game sometimes spawns an Advent guy that's just a head and a magnet lmg. No other enemies spawn with him. He stands there the entire mission in one spot and needs to die for a "Kill all enemies" objective to register.

### ISSUE THREAD

**Issue by Whats-an-Airport** [Grobobobo/WarOfTheChosenRebalanced#8]
![20220523162741_1](https://user-images.githubusercontent.com/106243012/170248377-2ba2a140-78f1-4019-8f06-c78803c35724.jpg)

**Comment by Whats-an-Airport** [comment]
![20220516171828_1](https://user-images.githubusercontent.com/106243012/170249875-c3db60a7-0527-481c-ad2a-babf342f6b2b.jpg)
I found another screen shot from an earlier mission

**Comment by Grobobobo** [comment]
Found the bug, Fixed Next Release.
