### ISSUE TITLE
Advanced Explosives replaces/hides Smoke Grenades

### ISSUE THREAD

**Issue by TwinuX** [Grobobobo/WarOfTheChosenRebalanced#81]
Advanced Explosives 'upgrades' currently-equipped Smoke Grenades into Smoke Bombs and hides the basic Smoke Grenade item, making it unusable (and also effectively creating a limit to the amount of Smoke Bombs XCOM owns, based on how many were equipped upon completing AE.)

**Comment by Grobobobo** [comment]
Should be fixed by now.
