### ISSUE TITLE
Gunner tank healing 1 missing hp when fired upon.

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#88]
Gunner tank with smoke medkit and some other item recovered 1 missing hp when fired upon regardless of whether the shot landed or not.

Here is a save in which it has always occurred and was consistent for me when I ran it
[save_gnrtnkhealaftershot.zip](https://github.com/Grobobobo/WarOfTheChosenRebalanced/files/9394286/save_gnrtnkhealaftershot.zip)
.

Here is the modlist being used
[GTO.txt](https://github.com/Grobobobo/WarOfTheChosenRebalanced/files/9394307/GTO.txt)

**Comment by Grobobobo** [comment]
Should be Fixed now.
