### ISSUE TITLE
Shinobi cant use slash before suign primary weapon (dev build 4)

### ISSUE THREAD

**Issue by Acithedj** [Grobobobo/WarOfTheChosenRebalanced#96]
Shinobi cant use slash before suign primary weapon (dev build 4)

**Comment by Grobobobo** [comment]
What does that even mean?

**Comment by Acithedj** [comment]
Hm, was late so my description is a bit lacking:) So I noticed over 2-3 missions that shinobis couldnt use the slash attack the first time i needed it. I used my SMG instead and then the ability worked fine. When i move the shinobi ajdacent to enemy the first time the ability is greyed and ui says no targets in range, though the enemy is there next to me. After i used my pirmary weapon insted all was fine for the rest of the mission

**Comment by Grobobobo** [comment]
The slash works fine for me, maybe it was a visual positioning error?

**Comment by Acithedj** [comment]
No, it was not happened across few missions now on different soldiers consistently. Ill try to teleport soldier via console and back again, or load the save. But dev build 3 was ok

**Comment by Acithedj** [comment]
Grobo, I started new dev build 4.1 campaign and all was fine now. It was probably just some glitch then. False alarm
